version: '3.2'

services:
 
  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql 
    restart: always
    environment:
     - MYSQL_DATABASE=carshop
     - MYSQL_USER=brier
     - MYSQL_PASSWORD=sunnyday
     - MYSQL_ROOT_PASSWORD=root
     - TZ=Europe/Moscow
    ports:
     - 3376:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    
  payara:
    container_name: payara
    build:
      context: .
      dockerfile: ./docker/payara/Dockerfile
    restart: always
    ports:
      - 8085:8080
      - 4949:4848
